# -*- coding: utf-8 -*-
"""Mini Project1-LEE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17--njVjpfq3oRLh_ZPfattEMSAiKAOSR
"""

# ✅ 1. 필수 라이브러리 설치
!pip install streamlit pyngrok --quiet

# ✅ 2. ngrok 인증 토큰 등록 (👉 ngrok 가입 후 받은 토큰으로 교체하세요)
# 토큰은 https://dashboard.ngrok.com/get-started/your-authtoken 에서 확인 가능
!ngrok config add-authtoken 2yP4Gt799Muq4gpuqxZ48CS7DQm_2coEa2vioWcycKYcDjAh3

# ✅ 3. Streamlit 앱 코드 저장 (Met Museum API 연동)
code = """
import streamlit as st
import requests

st.set_page_config(page_title='🎨 예술 작품 탐색기', layout='wide')
st.title("🖼️ 메트로폴리탄 미술관 작품 탐색기")

object_id = st.number_input("🔎 작품 ID를 입력하세요", min_value=1, value=436535)

@st.cache_data
def get_artwork(object_id):
    url = f"https://collectionapi.metmuseum.org/public/collection/v1/objects/{object_id}"
    res = requests.get(url)
    return res.json() if res.status_code == 200 else {}

if st.button("작품 조회"):
    data = get_artwork(object_id)
    if data.get("objectID"):
        st.subheader(data.get("title", "제목 없음"))
        if data.get("primaryImageSmall"):
            st.image(data["primaryImageSmall"], caption=data.get("artistDisplayName", ""), use_column_width=True)
        info_md = f'''
- 👨‍🎨 작가: **{data.get("artistDisplayName", "정보 없음")}**
- 🕰 제작연도: **{data.get("objectDate", "미상")}**
- 🏛 부서: {data.get("department", "정보 없음")}
- 📝 설명: {data.get("creditLine", "정보 없음")}
'''
        st.markdown(info_md)
    else:
        st.error("해당 ID에 대한 정보를 찾을 수 없습니다.")
"""

# ✅ 4. 코드 파일로 저장
with open("app.py", "w") as f:
    f.write(code)

# ✅ 5. ngrok으로 포트 터널링 연결
from pyngrok import ngrok
public_url = ngrok.connect(8501)
print(f"🌐 여기를 클릭해서 Streamlit 앱 열기 👉 {public_url}")

# ✅ 6. Streamlit 앱 실행
!streamlit run app.py &> /dev/null &

